/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISNADRegistry } from "./ISNADRegistry";
export type { ISNADStaking } from "./ISNADStaking";
export type { ISNADToken } from "./ISNADToken";
