/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ISNADRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TYPE_AGENT_CARD"
      | "TYPE_MODEL_CARD"
      | "TYPE_PROMPT"
      | "TYPE_RAW"
      | "TYPE_TOOL_SPEC"
      | "TYPE_TRAINING"
      | "TYPE_WORKFLOW"
      | "author"
      | "blockNumber"
      | "deprecate"
      | "exists"
      | "getChunkStatus"
      | "getResource"
      | "inscribe"
      | "inscribeChunk"
      | "isDeprecated"
      | "pendingChunks"
      | "supersededBy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChunkInscribed"
      | "ResourceDeprecated"
      | "ResourceInscribed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TYPE_AGENT_CARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TYPE_MODEL_CARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TYPE_PROMPT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TYPE_RAW", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TYPE_TOOL_SPEC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TYPE_TRAINING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TYPE_WORKFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "author", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "blockNumber",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deprecate",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "exists", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getChunkStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResource",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inscribe",
    values: [BytesLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inscribeChunk",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeprecated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingChunks",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supersededBy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "TYPE_AGENT_CARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TYPE_MODEL_CARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TYPE_PROMPT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TYPE_RAW", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TYPE_TOOL_SPEC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TYPE_TRAINING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TYPE_WORKFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "author", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deprecate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChunkStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "inscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inscribeChunk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDeprecated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingChunks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supersededBy",
    data: BytesLike
  ): Result;
}

export namespace ChunkInscribedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    chunkIndex: BigNumberish,
    totalChunks: BigNumberish,
    author: AddressLike
  ];
  export type OutputTuple = [
    contentHash: string,
    chunkIndex: bigint,
    totalChunks: bigint,
    author: string
  ];
  export interface OutputObject {
    contentHash: string;
    chunkIndex: bigint;
    totalChunks: bigint;
    author: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResourceDeprecatedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    supersededBy: BytesLike,
    author: AddressLike
  ];
  export type OutputTuple = [
    contentHash: string,
    supersededBy: string,
    author: string
  ];
  export interface OutputObject {
    contentHash: string;
    supersededBy: string;
    author: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResourceInscribedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    resourceType: BigNumberish,
    author: AddressLike,
    blockNumber: BigNumberish,
    metadata: string
  ];
  export type OutputTuple = [
    contentHash: string,
    resourceType: bigint,
    author: string,
    blockNumber: bigint,
    metadata: string
  ];
  export interface OutputObject {
    contentHash: string;
    resourceType: bigint;
    author: string;
    blockNumber: bigint;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISNADRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ISNADRegistry;
  waitForDeployment(): Promise<this>;

  interface: ISNADRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TYPE_AGENT_CARD: TypedContractMethod<[], [bigint], "view">;

  TYPE_MODEL_CARD: TypedContractMethod<[], [bigint], "view">;

  TYPE_PROMPT: TypedContractMethod<[], [bigint], "view">;

  TYPE_RAW: TypedContractMethod<[], [bigint], "view">;

  TYPE_TOOL_SPEC: TypedContractMethod<[], [bigint], "view">;

  TYPE_TRAINING: TypedContractMethod<[], [bigint], "view">;

  TYPE_WORKFLOW: TypedContractMethod<[], [bigint], "view">;

  author: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  blockNumber: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  deprecate: TypedContractMethod<
    [contentHash: BytesLike, newContentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  exists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getChunkStatus: TypedContractMethod<
    [contentHash: BytesLike],
    [
      [boolean, bigint, bigint, string] & {
        pending: boolean;
        received: bigint;
        total: bigint;
        chunkAuthor: string;
      }
    ],
    "view"
  >;

  getResource: TypedContractMethod<
    [contentHash: BytesLike],
    [
      [boolean, string, bigint, string] & {
        inscribed: boolean;
        resourceAuthor: string;
        inscribedBlock: bigint;
        successor: string;
      }
    ],
    "view"
  >;

  inscribe: TypedContractMethod<
    [
      contentHash: BytesLike,
      resourceType: BigNumberish,
      metadata: string,
      content: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  inscribeChunk: TypedContractMethod<
    [
      contentHash: BytesLike,
      chunkIndex: BigNumberish,
      totalChunks: BigNumberish,
      resourceType: BigNumberish,
      metadata: string,
      chunkData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isDeprecated: TypedContractMethod<
    [contentHash: BytesLike],
    [boolean],
    "view"
  >;

  pendingChunks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string] & {
        contentHash: string;
        totalChunks: bigint;
        receivedChunks: bigint;
        author: string;
      }
    ],
    "view"
  >;

  supersededBy: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TYPE_AGENT_CARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TYPE_MODEL_CARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TYPE_PROMPT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TYPE_RAW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TYPE_TOOL_SPEC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TYPE_TRAINING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TYPE_WORKFLOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "author"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "blockNumber"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deprecate"
  ): TypedContractMethod<
    [contentHash: BytesLike, newContentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getChunkStatus"
  ): TypedContractMethod<
    [contentHash: BytesLike],
    [
      [boolean, bigint, bigint, string] & {
        pending: boolean;
        received: bigint;
        total: bigint;
        chunkAuthor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResource"
  ): TypedContractMethod<
    [contentHash: BytesLike],
    [
      [boolean, string, bigint, string] & {
        inscribed: boolean;
        resourceAuthor: string;
        inscribedBlock: bigint;
        successor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "inscribe"
  ): TypedContractMethod<
    [
      contentHash: BytesLike,
      resourceType: BigNumberish,
      metadata: string,
      content: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "inscribeChunk"
  ): TypedContractMethod<
    [
      contentHash: BytesLike,
      chunkIndex: BigNumberish,
      totalChunks: BigNumberish,
      resourceType: BigNumberish,
      metadata: string,
      chunkData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDeprecated"
  ): TypedContractMethod<[contentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingChunks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string] & {
        contentHash: string;
        totalChunks: bigint;
        receivedChunks: bigint;
        author: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supersededBy"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvent(
    key: "ChunkInscribed"
  ): TypedContractEvent<
    ChunkInscribedEvent.InputTuple,
    ChunkInscribedEvent.OutputTuple,
    ChunkInscribedEvent.OutputObject
  >;
  getEvent(
    key: "ResourceDeprecated"
  ): TypedContractEvent<
    ResourceDeprecatedEvent.InputTuple,
    ResourceDeprecatedEvent.OutputTuple,
    ResourceDeprecatedEvent.OutputObject
  >;
  getEvent(
    key: "ResourceInscribed"
  ): TypedContractEvent<
    ResourceInscribedEvent.InputTuple,
    ResourceInscribedEvent.OutputTuple,
    ResourceInscribedEvent.OutputObject
  >;

  filters: {
    "ChunkInscribed(bytes32,uint16,uint16,address)": TypedContractEvent<
      ChunkInscribedEvent.InputTuple,
      ChunkInscribedEvent.OutputTuple,
      ChunkInscribedEvent.OutputObject
    >;
    ChunkInscribed: TypedContractEvent<
      ChunkInscribedEvent.InputTuple,
      ChunkInscribedEvent.OutputTuple,
      ChunkInscribedEvent.OutputObject
    >;

    "ResourceDeprecated(bytes32,bytes32,address)": TypedContractEvent<
      ResourceDeprecatedEvent.InputTuple,
      ResourceDeprecatedEvent.OutputTuple,
      ResourceDeprecatedEvent.OutputObject
    >;
    ResourceDeprecated: TypedContractEvent<
      ResourceDeprecatedEvent.InputTuple,
      ResourceDeprecatedEvent.OutputTuple,
      ResourceDeprecatedEvent.OutputObject
    >;

    "ResourceInscribed(bytes32,uint8,address,uint256,string)": TypedContractEvent<
      ResourceInscribedEvent.InputTuple,
      ResourceInscribedEvent.OutputTuple,
      ResourceInscribedEvent.OutputObject
    >;
    ResourceInscribed: TypedContractEvent<
      ResourceInscribedEvent.InputTuple,
      ResourceInscribedEvent.OutputTuple,
      ResourceInscribedEvent.OutputObject
    >;
  };
}
