/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ISNADOracle {
  export type FlagStruct = {
    resourceHash: BytesLike;
    flagger: AddressLike;
    deposit: BigNumberish;
    evidenceHash: BytesLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    juryDeadline: BigNumberish;
    voteCount: BigNumberish;
    guiltyVotes: BigNumberish;
  };

  export type FlagStructOutput = [
    resourceHash: string,
    flagger: string,
    deposit: bigint,
    evidenceHash: string,
    status: bigint,
    createdAt: bigint,
    juryDeadline: bigint,
    voteCount: bigint,
    guiltyVotes: bigint
  ] & {
    resourceHash: string;
    flagger: string;
    deposit: bigint;
    evidenceHash: string;
    status: bigint;
    createdAt: bigint;
    juryDeadline: bigint;
    voteCount: bigint;
    guiltyVotes: bigint;
  };
}

export interface ISNADOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "activeFlag"
      | "addToJurorPool"
      | "appeal"
      | "appealMultiplier"
      | "batchAddToJurorPool"
      | "executeSlash"
      | "finalizeVerdict"
      | "flagResource"
      | "flags"
      | "getFlag"
      | "getJurorPoolSize"
      | "getJury"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hasVoted"
      | "isInJurorPool"
      | "isJuror"
      | "jurorPool"
      | "jurors"
      | "juryList"
      | "jurySize"
      | "minFlagDeposit"
      | "renounceRole"
      | "revokeRole"
      | "selectJury"
      | "setJurySize"
      | "setMinFlagDeposit"
      | "setStakingContract"
      | "setVotingPeriod"
      | "stakingContract"
      | "supermajorityBps"
      | "supportsInterface"
      | "vote"
      | "votingPeriod"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FlagAppealed"
      | "JurorVoted"
      | "JurySelected"
      | "ResourceFlagged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SlashExecuted"
      | "VerdictReached"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeFlag",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToJurorPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "appeal", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "appealMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddToJurorPool",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSlash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeVerdict",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flagResource",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "flags", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getFlag", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getJurorPoolSize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getJury", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInJurorPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isJuror",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jurorPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jurors",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "juryList",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jurySize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minFlagDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "selectJury",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setJurySize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinFlagDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supermajorityBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "activeFlag", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addToJurorPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "appealMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAddToJurorPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSlash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flags", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFlag", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJurorPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInJurorPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isJuror", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jurorPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jurors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "juryList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jurySize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minFlagDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "selectJury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setJurySize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinFlagDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supermajorityBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriod",
    data: BytesLike
  ): Result;
}

export namespace FlagAppealedEvent {
  export type InputTuple = [
    flagId: BytesLike,
    appellant: AddressLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [
    flagId: string,
    appellant: string,
    deposit: bigint
  ];
  export interface OutputObject {
    flagId: string;
    appellant: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorVotedEvent {
  export type InputTuple = [
    flagId: BytesLike,
    juror: AddressLike,
    guilty: boolean
  ];
  export type OutputTuple = [flagId: string, juror: string, guilty: boolean];
  export interface OutputObject {
    flagId: string;
    juror: string;
    guilty: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurySelectedEvent {
  export type InputTuple = [flagId: BytesLike, jurors: AddressLike[]];
  export type OutputTuple = [flagId: string, jurors: string[]];
  export interface OutputObject {
    flagId: string;
    jurors: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResourceFlaggedEvent {
  export type InputTuple = [
    flagId: BytesLike,
    resourceHash: BytesLike,
    flagger: AddressLike,
    deposit: BigNumberish,
    evidenceHash: BytesLike
  ];
  export type OutputTuple = [
    flagId: string,
    resourceHash: string,
    flagger: string,
    deposit: bigint,
    evidenceHash: string
  ];
  export interface OutputObject {
    flagId: string;
    resourceHash: string;
    flagger: string;
    deposit: bigint;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashExecutedEvent {
  export type InputTuple = [
    resourceHash: BytesLike,
    totalSlashed: BigNumberish
  ];
  export type OutputTuple = [resourceHash: string, totalSlashed: bigint];
  export interface OutputObject {
    resourceHash: string;
    totalSlashed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictReachedEvent {
  export type InputTuple = [
    flagId: BytesLike,
    resourceHash: BytesLike,
    verdict: BigNumberish,
    guiltyVotes: BigNumberish,
    totalVotes: BigNumberish
  ];
  export type OutputTuple = [
    flagId: string,
    resourceHash: string,
    verdict: bigint,
    guiltyVotes: bigint,
    totalVotes: bigint
  ];
  export interface OutputObject {
    flagId: string;
    resourceHash: string;
    verdict: bigint;
    guiltyVotes: bigint;
    totalVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISNADOracle extends BaseContract {
  connect(runner?: ContractRunner | null): ISNADOracle;
  waitForDeployment(): Promise<this>;

  interface: ISNADOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  activeFlag: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  addToJurorPool: TypedContractMethod<
    [jurorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  appeal: TypedContractMethod<[flagId: BytesLike], [void], "payable">;

  appealMultiplier: TypedContractMethod<[], [bigint], "view">;

  batchAddToJurorPool: TypedContractMethod<
    [addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  executeSlash: TypedContractMethod<
    [resourceHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  finalizeVerdict: TypedContractMethod<
    [flagId: BytesLike],
    [void],
    "nonpayable"
  >;

  flagResource: TypedContractMethod<
    [resourceHash: BytesLike, evidenceHash: BytesLike],
    [string],
    "payable"
  >;

  flags: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        resourceHash: string;
        flagger: string;
        deposit: bigint;
        evidenceHash: string;
        status: bigint;
        createdAt: bigint;
        juryDeadline: bigint;
        voteCount: bigint;
        guiltyVotes: bigint;
      }
    ],
    "view"
  >;

  getFlag: TypedContractMethod<
    [flagId: BytesLike],
    [ISNADOracle.FlagStructOutput],
    "view"
  >;

  getJurorPoolSize: TypedContractMethod<[], [bigint], "view">;

  getJury: TypedContractMethod<[flagId: BytesLike], [string[]], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [flagId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  isInJurorPool: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isJuror: TypedContractMethod<
    [flagId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  jurorPool: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  jurors: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [boolean, boolean, boolean] & {
        selected: boolean;
        voted: boolean;
        votedGuilty: boolean;
      }
    ],
    "view"
  >;

  juryList: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  jurySize: TypedContractMethod<[], [bigint], "view">;

  minFlagDeposit: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  selectJury: TypedContractMethod<[flagId: BytesLike], [void], "nonpayable">;

  setJurySize: TypedContractMethod<
    [_jurySize: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinFlagDeposit: TypedContractMethod<
    [_minDeposit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStakingContract: TypedContractMethod<
    [_stakingContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setVotingPeriod: TypedContractMethod<
    [_votingPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakingContract: TypedContractMethod<[], [string], "view">;

  supermajorityBps: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  vote: TypedContractMethod<
    [flagId: BytesLike, guilty: boolean],
    [void],
    "nonpayable"
  >;

  votingPeriod: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeFlag"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "addToJurorPool"
  ): TypedContractMethod<[jurorAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "appeal"
  ): TypedContractMethod<[flagId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "appealMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchAddToJurorPool"
  ): TypedContractMethod<[addresses: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeSlash"
  ): TypedContractMethod<[resourceHash: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeVerdict"
  ): TypedContractMethod<[flagId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "flagResource"
  ): TypedContractMethod<
    [resourceHash: BytesLike, evidenceHash: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "flags"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        resourceHash: string;
        flagger: string;
        deposit: bigint;
        evidenceHash: string;
        status: bigint;
        createdAt: bigint;
        juryDeadline: bigint;
        voteCount: bigint;
        guiltyVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFlag"
  ): TypedContractMethod<
    [flagId: BytesLike],
    [ISNADOracle.FlagStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJurorPoolSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJury"
  ): TypedContractMethod<[flagId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [flagId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInJurorPool"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isJuror"
  ): TypedContractMethod<
    [flagId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "jurorPool"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "jurors"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [boolean, boolean, boolean] & {
        selected: boolean;
        voted: boolean;
        votedGuilty: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "juryList"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "jurySize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minFlagDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "selectJury"
  ): TypedContractMethod<[flagId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setJurySize"
  ): TypedContractMethod<[_jurySize: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinFlagDeposit"
  ): TypedContractMethod<[_minDeposit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingContract"
  ): TypedContractMethod<[_stakingContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVotingPeriod"
  ): TypedContractMethod<[_votingPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supermajorityBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [flagId: BytesLike, guilty: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FlagAppealed"
  ): TypedContractEvent<
    FlagAppealedEvent.InputTuple,
    FlagAppealedEvent.OutputTuple,
    FlagAppealedEvent.OutputObject
  >;
  getEvent(
    key: "JurorVoted"
  ): TypedContractEvent<
    JurorVotedEvent.InputTuple,
    JurorVotedEvent.OutputTuple,
    JurorVotedEvent.OutputObject
  >;
  getEvent(
    key: "JurySelected"
  ): TypedContractEvent<
    JurySelectedEvent.InputTuple,
    JurySelectedEvent.OutputTuple,
    JurySelectedEvent.OutputObject
  >;
  getEvent(
    key: "ResourceFlagged"
  ): TypedContractEvent<
    ResourceFlaggedEvent.InputTuple,
    ResourceFlaggedEvent.OutputTuple,
    ResourceFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SlashExecuted"
  ): TypedContractEvent<
    SlashExecutedEvent.InputTuple,
    SlashExecutedEvent.OutputTuple,
    SlashExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictReached"
  ): TypedContractEvent<
    VerdictReachedEvent.InputTuple,
    VerdictReachedEvent.OutputTuple,
    VerdictReachedEvent.OutputObject
  >;

  filters: {
    "FlagAppealed(bytes32,address,uint256)": TypedContractEvent<
      FlagAppealedEvent.InputTuple,
      FlagAppealedEvent.OutputTuple,
      FlagAppealedEvent.OutputObject
    >;
    FlagAppealed: TypedContractEvent<
      FlagAppealedEvent.InputTuple,
      FlagAppealedEvent.OutputTuple,
      FlagAppealedEvent.OutputObject
    >;

    "JurorVoted(bytes32,address,bool)": TypedContractEvent<
      JurorVotedEvent.InputTuple,
      JurorVotedEvent.OutputTuple,
      JurorVotedEvent.OutputObject
    >;
    JurorVoted: TypedContractEvent<
      JurorVotedEvent.InputTuple,
      JurorVotedEvent.OutputTuple,
      JurorVotedEvent.OutputObject
    >;

    "JurySelected(bytes32,address[])": TypedContractEvent<
      JurySelectedEvent.InputTuple,
      JurySelectedEvent.OutputTuple,
      JurySelectedEvent.OutputObject
    >;
    JurySelected: TypedContractEvent<
      JurySelectedEvent.InputTuple,
      JurySelectedEvent.OutputTuple,
      JurySelectedEvent.OutputObject
    >;

    "ResourceFlagged(bytes32,bytes32,address,uint256,bytes32)": TypedContractEvent<
      ResourceFlaggedEvent.InputTuple,
      ResourceFlaggedEvent.OutputTuple,
      ResourceFlaggedEvent.OutputObject
    >;
    ResourceFlagged: TypedContractEvent<
      ResourceFlaggedEvent.InputTuple,
      ResourceFlaggedEvent.OutputTuple,
      ResourceFlaggedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SlashExecuted(bytes32,uint256)": TypedContractEvent<
      SlashExecutedEvent.InputTuple,
      SlashExecutedEvent.OutputTuple,
      SlashExecutedEvent.OutputObject
    >;
    SlashExecuted: TypedContractEvent<
      SlashExecutedEvent.InputTuple,
      SlashExecutedEvent.OutputTuple,
      SlashExecutedEvent.OutputObject
    >;

    "VerdictReached(bytes32,bytes32,uint8,uint256,uint256)": TypedContractEvent<
      VerdictReachedEvent.InputTuple,
      VerdictReachedEvent.OutputTuple,
      VerdictReachedEvent.OutputObject
    >;
    VerdictReached: TypedContractEvent<
      VerdictReachedEvent.InputTuple,
      VerdictReachedEvent.OutputTuple,
      VerdictReachedEvent.OutputObject
    >;
  };
}
